service:
  name: aws-nodejs-v8

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  get:
    handler: methods.get
    events:
      - http:
          method: get
          path: /
